### ISSUE TITLE
Updating from 0.2 to 0.3 resets tags

### ISSUE THREAD

**Issue by dben123456** [Issung/SorterExpress#18]
Updated to the new version and all my tags disappeared. Lucky for me I had a backup.

**Comment by Issung** [comment]
Hi there, sorry to hear that. As you know the program is in beta and there is no guarantees everything will work correctly. In the jump from 0.2 to 0.3 I completely rewrote how settings are stored. I will add a note to the release to notify people of this effect.

Speaking of managing tags, I hope you enjoy the new tag management interface in settings :)
![image](https://github.com/Issung/SorterExpress/assets/22212465/67820e07-884e-4eda-93bd-5f2459e11b7e)
