### ISSUE TITLE
Dunno where else to post this but I love this tool, it makes organizing my files 100 times easier and faster

### ISSUE THREAD

**Issue by Naturally-Delicious** [Issung/SorterExpress#19]
Really underrated tool. I love how automated everything is and the auto playing videos, it saves so much time and less clicking. 

The one thing I would add is ability to change the file name directly without removing it entirely (right now I have to copy the name, then paste it into the "Note" input box in order to change one aspect of the file name.

And if it's possible add more file formats to be supported like pdf, .mov, etc.

Thanks sir for this great invention, you have saved so much of a stranger's time. Looking forward to any updates if you are working on any.

**Comment by Issung** [comment]
Thanks for the wonderful feedback, stuff like this really makes it all worth it :)

About your 1st request, how does this sound:
While your input is focused on the note field if you press CTRL + C while it is empty, it copies the current filename into the note field, does that sound satisfactory? If so I will try and implement it for you, if not, let me know your idea :)

About your 2nd request: 
PDF is a cool idea but would require some effort I don't really have time for at the moment (it would work in neither the image viewer or video viewer). The .mov file is probably doable though if I just add it to the allow list, I'll try that out. Any other file formats that fall into either image/video that you'd like me to add?

**Comment by Naturally-Delicious** [comment]
> Thanks for the wonderful feedback, stuff like this really makes it all worth it :)
> 
> About your 1st request, how does this sound: While your input is focused on the note field if you press CTRL + C while it is empty, it copies the current filename into the note field, does that sound satisfactory? If so I will try and implement it for you, if not, let me know your idea :)
> 
> About your 2nd request: PDF is a cool idea but would require some effort I don't really have time for at the moment (it would work in neither the image viewer or video viewer). The .mov file is probably doable though if I just add it to the allow list, I'll try that out. Any other file formats that fall into either image/video that you'd like me to add?

Hey! Sorry for the late response, don't check this often haha.

1. That sounds perfect!
2. .mov would be extremely convenient! My iPhone has a lot of .mov, would be awesome if I could sort through that, it's been sitting for a while lol. All my .mp4, which over thousands and thousands, SorterExpress has helped me categorize and name them with such ease.

Another file format that I use but not as often is .mkv. .HEIC would be a nice addition too, but I've been moving away from iOS sandboxed crap so again, not as important.

Once again thanks for this, I use it each time I sort through my files and I beg everyone on Reddit to use it lol.

**Comment by Issung** [comment]
I have added the new features you requested and created a new release, available at: https://github.com/Issung/SorterExpress/releases.

I'm glad to hear you find great use of my software, please consider donating if you are able, it would be much appreciated :) https://ko-fi.com/issung
